//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arduino.Firmata.Serial {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arduino.Firmata.Serial.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot convert non-BCD data. 的本地化字符串。
        /// </summary>
        internal static string ArgumentEx_CannotConvertBcd {
            get {
                return ResourceManager.GetString("ArgumentEx_CannotConvertBcd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Channel number must be between 0 and 15. 的本地化字符串。
        /// </summary>
        internal static string ArgumentEx_ChannelRange0_15 {
            get {
                return ResourceManager.GetString("ArgumentEx_ChannelRange0_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String must contain digits only. 的本地化字符串。
        /// </summary>
        internal static string ArgumentEx_DigitStringOnly {
            get {
                return ResourceManager.GetString("ArgumentEx_DigitStringOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address must be between 0 and 1,023. 的本地化字符串。
        /// </summary>
        internal static string ArgumentEx_I2cAddressRange {
            get {
                return ResourceManager.GetString("ArgumentEx_I2cAddressRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interval must be between 0 and 16,383 milliseconds. 的本地化字符串。
        /// </summary>
        internal static string ArgumentEx_I2cInterval {
            get {
                return ResourceManager.GetString("ArgumentEx_I2cInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum pulse width must be between 0 and 16,383 milliseconds. 的本地化字符串。
        /// </summary>
        internal static string ArgumentEx_MaxPulseWidth {
            get {
                return ResourceManager.GetString("ArgumentEx_MaxPulseWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum pulse width is greater than maximum pulse width. 的本地化字符串。
        /// </summary>
        internal static string ArgumentEx_MinMaxPulse {
            get {
                return ResourceManager.GetString("ArgumentEx_MinMaxPulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum pulse width must be between 0 and 16,383 milliseconds. 的本地化字符串。
        /// </summary>
        internal static string ArgumentEx_MinPulseWidth {
            get {
                return ResourceManager.GetString("ArgumentEx_MinPulseWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value cannot be negative. 的本地化字符串。
        /// </summary>
        internal static string ArgumentEx_NoNegativeValue {
            get {
                return ResourceManager.GetString("ArgumentEx_NoNegativeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String argument can not be null or empty. 的本地化字符串。
        /// </summary>
        internal static string ArgumentEx_NotNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentEx_NotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin number must be between 0 and 127. 的本地化字符串。
        /// </summary>
        internal static string ArgumentEx_PinRange0_127 {
            get {
                return ResourceManager.GetString("ArgumentEx_PinRange0_127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin must be between 0 and 7. 的本地化字符串。
        /// </summary>
        internal static string ArgumentEx_PinRange0_7 {
            get {
                return ResourceManager.GetString("ArgumentEx_PinRange0_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port number must be between 0 and 15. 的本地化字符串。
        /// </summary>
        internal static string ArgumentEx_PortRange0_15 {
            get {
                return ResourceManager.GetString("ArgumentEx_PortRange0_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value must be greater than zero. 的本地化字符串。
        /// </summary>
        internal static string ArgumentEx_PositiveValue {
            get {
                return ResourceManager.GetString("ArgumentEx_PositiveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sampling interval must be between 0 and 16,383 milliseconds. 的本地化字符串。
        /// </summary>
        internal static string ArgumentEx_SamplingInterval {
            get {
                return ResourceManager.GetString("ArgumentEx_SamplingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value must be between 0 and 16,383. 的本地化字符串。
        /// </summary>
        internal static string ArgumentEx_ValueRange0_16383 {
            get {
                return ResourceManager.GetString("ArgumentEx_ValueRange0_16383", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value must be betwen 0 and 255. 的本地化字符串。
        /// </summary>
        internal static string ArgumentEx_ValueRange0_255 {
            get {
                return ResourceManager.GetString("ArgumentEx_ValueRange0_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin is not supported. 的本地化字符串。
        /// </summary>
        internal static string InvalidOpEx_PinNotSupported {
            get {
                return ResourceManager.GetString("InvalidOpEx_PinNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commandbyte {0:X} is not implemented. 的本地化字符串。
        /// </summary>
        internal static string NotImplementedEx_Command {
            get {
                return ResourceManager.GetString("NotImplementedEx_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command must be [0x01 .. 0x0F] 的本地化字符串。
        /// </summary>
        internal static string OutOfRange_UserDefinedSysExCommand {
            get {
                return ResourceManager.GetString("OutOfRange_UserDefinedSysExCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The command parsing buffer is full. 的本地化字符串。
        /// </summary>
        internal static string OverflowEx_CmdBufferFull {
            get {
                return ResourceManager.GetString("OverflowEx_CmdBufferFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Received message queue is full. 的本地化字符串。
        /// </summary>
        internal static string OverflowEx_MsgBufferFull {
            get {
                return ResourceManager.GetString("OverflowEx_MsgBufferFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The received strings buffer is full. 的本地化字符串。
        /// </summary>
        internal static string OverflowEx_StringBufferFull {
            get {
                return ResourceManager.GetString("OverflowEx_StringBufferFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait condition for {0} message timed out. 的本地化字符串。
        /// </summary>
        internal static string TimeoutEx_WaitMessage {
            get {
                return ResourceManager.GetString("TimeoutEx_WaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait condition for string read in {0} mode timed out. 的本地化字符串。
        /// </summary>
        internal static string TimeoutEx_WaitStringRequest {
            get {
                return ResourceManager.GetString("TimeoutEx_WaitStringRequest", resourceCulture);
            }
        }
    }
}
